"""Add profile fields to users

Revision ID: 9e83ff457874
Revises: df201b134616
Create Date: 2025-11-05 12:31:03.938126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e83ff457874'
down_revision = 'df201b134616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
