# In the new migration file

import sqlalchemy as sa
from alembic import op
import random
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'your_new_revision_id'
down_revision = 'previous_revision_id'
branch_labels = None
depends_on = None


def generate_order_number(created_at=None):
    """Generate order number for existing records"""
    timestamp = created_at.strftime('%Y%m%d%H%M%S') if created_at else datetime.utcnow().strftime('%Y%m%d%H%M%S')
    random_num = random.randint(1000, 9999)
    return f'ORD-{timestamp}-{random_num}'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add column as nullable first
    op.add_column('orders', sa.Column('order_number', sa.String(length=50), nullable=True))
    
    # Step 2: Fill in values for existing records
    connection = op.get_bind()
    
    # Get existing orders
    result = connection.execute("SELECT id, created_at FROM orders")
    orders = result.fetchall()
    
    for order in orders:
        order_number = generate_order_number(order.created_at)
        connection.execute(
            "UPDATE orders SET order_number = %s WHERE id = %s",
            (order_number, order.id)
        )
    
    # Step 3: Now make the column NOT NULL
    op.alter_column('orders', 'order_number',
                    existing_type=sa.String(length=50),
                    nullable=False)
    
    # Step 4: Add unique constraint
    op.create_unique_constraint('uq_order_number', 'orders', ['order_number'])
    
    # Add other columns that were in your original migration
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_amount', sa.Float(), nullable=True))
    # ... add all other columns
    
    # Fill default values for other columns
    connection.execute("UPDATE orders SET subtotal = total_amount WHERE subtotal IS NULL")
    connection.execute("UPDATE orders SET tax_amount = 0 WHERE tax_amount IS NULL")
    connection.execute("UPDATE orders SET shipping_amount = 0 WHERE shipping_amount IS NULL")
    
    # Make other columns NOT NULL after filling values
    op.alter_column('orders', 'subtotal', nullable=False)
    op.alter_column('orders', 'tax_amount', nullable=False)
    op.alter_column('orders', 'shipping_amount', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_number', 'orders', type_='unique')
    op.drop_column('orders', 'order_number')
    op.drop_column('orders', 'shipping_amount')
    op.drop_column('orders', 'tax_amount')
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###