"""initial migration null=false brand-id

Revision ID: 299e1230558f
Revises: 5a1367df779b
Create Date: 2025-10-21 15:59:25.225364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299e1230558f'
down_revision = '5a1367df779b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
