"""Add order_number column to orders table

Revision ID: 4797b2237329
Revises: cd18c2f6669e
Create Date: 2026-01-02 12:41:53.994604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4797b2237329'
down_revision = 'cd18c2f6669e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('customization_data', sa.JSON(), nullable=True))
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('product_title')
        batch_op.drop_column('product_price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('tax_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shipping_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('carrier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('shipping_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['order_number'])
        batch_op.drop_constraint(batch_op.f('orders_product_id_fkey'), type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('result_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('result_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('card_last_four', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_brand', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('refund_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('refund_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('initiated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('payments_transaction_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['payment_reference'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('payments_transaction_id_key'), ['transaction_id'])
        batch_op.drop_column('failed_at')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('initiated_at')
        batch_op.drop_column('meta_info')
        batch_op.drop_column('refund_reason')
        batch_op.drop_column('refund_amount')
        batch_op.drop_column('card_brand')
        batch_op.drop_column('card_last_four')
        batch_op.drop_column('account_number')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('result_description')
        batch_op.drop_column('result_code')
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('currency')
        batch_op.drop_column('payment_reference')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('orders_product_id_fkey'), 'products', ['product_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('shipping_address',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('estimated_delivery')
        batch_op.drop_column('carrier')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('notes')
        batch_op.drop_column('billing_address')
        batch_op.drop_column('shipping_amount')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('order_number')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.alter_column('size',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('customization_data')
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
