"""empty message

Revision ID: 576a473e8db4
Revises: a486fe28229f
Create Date: 2025-10-17 15:09:38.047151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576a473e8db4'
down_revision = 'a486fe28229f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('merchant_request_id')

    # ### end Alembic commands ###
