"""Rebuild models including 3D fields for products

Revision ID: a486fe28229f
Revises: 
Create Date: 2025-10-16 17:19:47.914042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a486fe28229f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_3d_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('has_3d_model', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('model_scale', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('model_position', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('model_position')
        batch_op.drop_column('model_scale')
        batch_op.drop_column('has_3d_model')
        batch_op.drop_column('model_3d_url')

    # ### end Alembic commands ###
